---
- hosts: website
  gather_facts: yes
  tasks:
    - name: Fetch the latest code from the repository
      git:
        repo: 'https://github.com/dominick253/dominick253.github.io.git'
        dest: '/root/dominick253.github.io'
        version: main
        accept_hostkey: yes
        force: yes

#    - name: Include the sensitive variables
#      include_vars:
#        file: sensitive_vars.yml
#       
#    - name: Create .env file from template
#      template:
#        src: env.j2
#      dest: '/root/dominick253.github.io/.env'
#      mode: '0600'
#      no_log: true

    - name: Install any new dependencies
      npm:
        path: '/root/dominick253.github.io'
        state: present

    - name: Restart the Node.js application (using systemctl)
      systemd:
        name: dominickp
        state: restarted


